### ISSUE TITLE
az emailhez és a fölötte lévő ikonhoz jó lenne linkelni a mailto: taget, hogy kattintásra megnyíljon a levelező

### ISSUE THREAD

**Issue by neurodiversitas** [neurodiversitas/neurodiversitas#2]

**Comment by neurodiversitas** [comment]
Engem mindig zavar, amikor ilyen esetben megnyílik a levelező. Általában az emberek hogy vannak vele?

**Comment by zsiraf** [comment]
Akkor úgy veszem, hogy mailto csak engem zavar, megcsinálom.

**Comment by elnok** [comment]
Szerintem is utálják az emberek, de ez az egyszerű megoldás. alternatíva a submit form. de ahhoz szokott kelleni engine script. ami már nem statikus weboldal. vagy van vmi email küldő oldal aminek van embedded kódja. lehet, hogy a mailchimpnek van. vagy lehet keresni mail send form vagy submit form embedded kulcsszavakra. de így is jó neke, balázs magyarázta még hogy a spammerek begyűjtik így. hát nem tudom. ha macerás minden más akkor maradjon!
