### ISSUE TITLE
cél, manifesztum

### ISSUE THREAD

**Issue by elnok** [neurodiversitas/neurodiversitas#4]
Kellene bele:

az alapítvány célja, és	manifesztum (akár az ami	Judit könyvében	van:

2015-ben alakultunk azzal a céllal, hogy megteremtsük azt a társadalmi környezetet, amelyben a neurális kisebbségek – autisták, ADHD-sek és más, rendhagyó agyi felépítéssel élő személyek – és a többségi társadalom konstruktívan együttműködve egymással, képessé válnak egymást kölcsönösen segíteni specifikus problémáik megoldásában, win-win kapcsolat formájában.
Jelenleg az Aura Egyesület mellett működünk, a programok egy részét bonyolítjuk. Középtávú célunk az autisták önálló élethez való segítése, ezen belül tehetségkutatás, munkavállalásban, elhelyezkedésben segítés, támogatott életvitel biztosítása.
Már-már közhely, hogy a „fura zsenik” viszik előre a világot, nekik köszönhetünk rengeteg mindent, amit a saját értékünknek is tekintünk. Ilyen zsenik például: Leonardo da Vinci a polihisztor művész, Albert Einstein, Isaac Newton, W. A. Mozart és még sokan mások. A különleges embereknek rendszerint vannak tanulási, beilleszkedési nehézségeik, hiperaktívak, vagy egyszerűen különös szokásaik, rigolyáik vannak, amelyeket a környezetük nehezen visel el. A neurális mássággal élő emberek többségét a társadalom fogyatékosnak bélyegzi, és kirekeszti. Ezeken a területeken kívánunk segítséget nyújtani számukra annak érdekében, hogy a bennük rejlő értékeket maradéktalanul kibontakoztathassák. 
Képviseljük a többség érdekeit is abban, hogy a saját maguk egyéni szintjén egészségesen változatos, és gondolkodásmódban színes-izgalmas emberi környezet vegyen mindenkit körül, illetve egy folyamatosan megújuló, divergens kulturális közegben éljük az életünket (és abban indítsuk útjukra a gyermekeinket). Ezért segítjük a neurális kisebbségeket annyira, amennyi segítséget mi, egyénileg és kulturális szinten igénylünk az ő irányukból. 
Alapítványunk ezt a küldetést vállalta fel – amiben mindkét fél nyertes – azzal szemben, amikor bélyegeket sütünk embercsoportokra, és az alapján ítéljük meg az emberek valódi hasznosságukat, értéküket. 
Segítjük, hogy neurodiverzitás kérdése, a neurális mássággal élő embertársaink társadalmi jelenléte a helyén legyen kezelve, biztosítjuk számukra az önmegvalósítás és kulturális kibontakozás szabad lehetőségét, hogy hasznos részei lehessenek a világunknak és hétköznapi környezetünknek. 
Tudatformáló tevékenységünkkel és példamutatásunkkal küzdünk azért, hogy a jelenlegi fogyatékos szemléletet, amely a „méltóságteljes élet és biztos távolság“ elvélre épül, felváltsa egy nyereséges viszony, az előítélettől mentes, kellően differenciáló, a másság értékeire való nyitottság, amely bizalommal és támogatólag tekint a szokatlan erőfeszítések mellett kitartó kreatív újítók szerepére.
Szeretnénk elérni, hogy a neurodiverzitás össztársadalmilag elfogadott, és a legmesszebbmenőkig támogatott érték legyen, és a kivételes agyműködéssel rendelkező embertársaink felfedező-újító-előmozdító munkássága közismert és elfogadott társadalmi szereppé váljon.

**Comment by zsiraf** [comment]
fenti szöveg a küldetés menüben
